version: '3.8'

services:
  dbt:
    image: xemuliam/dbt:duckdb
    container_name: dbt_duckdbt_task
    volumes:
      - .:/app
      - .dbt/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /app
    command: [ "dbt", "run" ]